spring:
  aop.proxy-target-class: true
  datasource:
    url: jdbc:postgresql://localhost:5532/movies
    username: movies_postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.default_schema: movies
      hibernate.id.new_generator_mappings: true

  mvc.view.prefix : /views/
  mvc.view.suffix : .html
flyway:
  enabled: true
  table: DB_MIGRATION_HISTORY
  sqlMigrationSuffix: .Final.sql
  schemas: movies
  health-checks:
    db-query: select now();